version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready","-U","user","-d","my_db","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  elt:
    build: ./elt
    container_name: elt_script
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./elt:/app
    command: ["tail","-f","/dev/null"]

volumes:
  db_data: